// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szifnmitaxeviqaikwlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6aWZubWl0YXhldmlxYWlrd2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDI5MzgsImV4cCI6MjA1OTI3ODkzOH0.qskfMDxgbbF4Wv_vbSV0XMg-Q-zxF-oNwMzJ7WZpv5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);