// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqwkyylnrzvbgxjszbmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxd2t5eWxucnp2Ymd4anN6Ym1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDU3MjYsImV4cCI6MjA1OTI4MTcyNn0.hdYNQ1znw7PlcHQstkUX5eEIjMNu_usCMfVTYu6aYWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);